### PR TITLE
Update attribute_driver.rb

### PR DESCRIPTION
**Pull request by mzdrahal**
The original code provoked the following error during my chef-client run (on omnibus 10.32.2-3).

ERROR: NameError: Cannot find a resource for k on ubuntu version 12.04

My change fixes this error.

### CODE REVIEW

**Comment by spheromak** [comment]
Interesting. Thanks for the compat fix @pluesch0r

**Comment by spheromak** [comment]
I will get the travis stuff fixed up sometime this week, merge and release a new version.

**Comment by Linuturk** [comment]
This PR fixes the problem for me as well. Can we get this merged? Seems your builds failed for unrelated reasons.

**Comment by spheromak** [comment]
yea sorry about this I was working on revamping all the CI, and got sidetracked.  Too many things going on at once. Merging to master now. Will cut a release when I get around to fixing all the CI.

**Pull request merged**
